### ISSUE TITLE
Put Watchdog stuff in Component

### ISSUE THREAD

**Issue by drmercer** [rmr662/RMR662-2013#1]
Disable Watchdog by default in `robotInit()`. When a critical Component thread starts, enable the Watchdog and feed it regularly in that thread.

**Comment by drmercer** [comment]
I need to find a way for multiple Components to feed the Watchdog at the same time without negating its purpose.

**Comment by mcoffin** [comment]
What I would do is make a custom watchdog that waits to be fed by all the components registered to it, then feeds the system watchdog.
