### ISSUE TITLE
Change Fluffy to use synchronization?

### ISSUE THREAD

**Issue by drmercer** [rmr662/RMR662-2013#3]
I might change Fluffy to use synchronized blocking to detect blocked components. Then Components don't have to necessarily be threads that check in with Fluffy; rather, Fluffy will check on the Components with a synchronized `ping()` method or something.

**Comment by mcoffin** [comment]
Smart idea, but won't it then be Fluffy's thread that's getting checked by ping() being called?

**Comment by drmercer** [comment]
I won't be doing this - the current system works just fine. If it ain't broke, don't fix it.
