### ISSUE TITLE
Change Climber to use updated wiring plan

### ISSUE THREAD

**Issue by drmercer** [rmr662/RMR662-2013#7]
The Climber code is designed for the horizontal hook pairs to be AND-ed together. Isn't the new plan to OR the vertical pairs together? (We may need to discuss this with Wiring.) @jkulik11

**Comment by jkulik11** [comment]
The code right now is working for anding, but it seems like oring would be better.

Sent from my Samsung Epic™ 4G TouchDan Mercer notifications@github.com wrote:The Climber code is designed for the horizontal hook pairs to be AND-ed together. Isn't the new plan to OR the vertical pairs together? (We may need to discuss this with Wiring.) @jkulik11

**Comment by drmercer** [comment]
NewClimber uses the _updated_ updated wiring plan.
